import { createClient } from "@supabase/supabase-js";

// Initialize Supabase client
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    "Missing Supabase environment variables: NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY"
  );
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Logs an agent action to the agent_logs table in Supabase
 * @param runId - Unique identifier for the pipeline run
 * @param agent - Name of the agent performing the action
 * @param input - Input provided to the agent
 * @param output - Output generated by the agent
 * @param metadata - Optional metadata about the action
 */
export async function logAgentAction(
  runId: string,
  agent: string,
  input: string,
  output: string,
  metadata?: any
): Promise<void> {
  try {
    const { error } = await supabase.from("agent_logs").insert({
      run_id: runId,
      agent,
      input,
      output,
      metadata,
      created_at: new Date().toISOString(),
    });

    if (error) {
      console.error("Error logging agent action to Supabase:", error);
      throw error;
    }
  } catch (error) {
    console.error("Failed to log agent action:", error);
    // Don't throw - logging failures shouldn't break the pipeline
    // but we'll log the error for debugging
  }
}
